export enum Headers {
  "questionnaire" = `Start your heat pump quote`,
  "email" = "Receive a copy of your estimate",
  "ownRent" = "Do you own or rent this property?",
  "typeOfProperty" = "What type of property is it?",
  "houseBedrooms" = "How many bedrooms does the property have?",
  "propetySize" = "How many storeys does your property have?",
  "basement" = "Do you have a basement?",
  "floorArea" = "What is the total floor area of your property?",
  "propertyBuilt" = "When was the property built?",
  "esm" = "Since the property was built, was it fitted with any of the following energy saving measures?",
  "esmWithEPC" = "Have any of the following energy saving measures been fitted since",
  "fuel" = "What is your main source of fuel for your heating?",
  "boilerType" = "Do you have a hot water cylinder?",
  "heatingSystem" = "What type of heating system do you currently have?",
  "contactUs" = "Please contact us",
  "builtFlat" = "As the property is a purpose built flat, it'll be easier for us to help you over the phone.",
  "cantInstall" = "We're not able to install a heat pump for you",
  "pleaseConfirmAddress" = "Please confirm the address for the property in your estimate",
}
